//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateModul {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal translations() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateModul.lang.translations", typeof(translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_Password_Retry
        {
            get
            {
                return ResourceManager.GetString("frmMain_Dlg_Password_Retry", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmVersion_MultipleBaseVersions1
        {
            get
            {
                return ResourceManager.GetString("frmVersion_MultipleBaseVersions1", resourceCulture);
            }
        }
        internal static string frmVersion_MultipleBaseVersions2
        {
            get
            {
                return ResourceManager.GetString("frmVersion_MultipleBaseVersions2", resourceCulture);
            }
        }

        internal static string frmDownload_LookingForVersions1
        {
            get
            {
                return ResourceManager.GetString("frmDownload_LookingForVersions1", resourceCulture);
            }
        }
        internal static string frmDownload_LookingForVersions2
        {
            get
            {
                return ResourceManager.GetString("frmDownload_LookingForVersions2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmVersion_FurtherMultipleBase1
        {
            get
            {
                return ResourceManager.GetString("frmVersion_FurtherMultipleBase1", resourceCulture);
            }
        }
        internal static string frmVersion_FurtherMultipleBase2
        {
            get
            {
                return ResourceManager.GetString("frmVersion_FurtherMultipleBase2", resourceCulture);
            }
        }



        internal static string frmInfo_NoVersion1
        {
            get
            {
                return ResourceManager.GetString("frmInfo_NoVersion1", resourceCulture);
            }
        }
        internal static string frmInfo_NoVersion2
        {
            get
            {
                return ResourceManager.GetString("frmInfo_NoVersion2", resourceCulture);
            }
        }


        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmVersion_MultipleVersions1
        {
            get
            {
                return ResourceManager.GetString("frmVersion_MultipleVersions1", resourceCulture);
            }
        }
        internal static string frmVersion_MultipleVersions2
        {
            get
            {
                return ResourceManager.GetString("frmVersion_MultipleVersions2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmVersion_BaseVersion1
        {
            get
            {
                return ResourceManager.GetString("frmVersion_BaseVersion1", resourceCulture);
            }
        }
        internal static string frmVersion_BaseVersion2
        {
            get
            {
                return ResourceManager.GetString("frmVersion_BaseVersion2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmVersion_SingleVersion1
        {
            get
            {
                return ResourceManager.GetString("frmVersion_SingleVersion1", resourceCulture);
            }
        }
        internal static string frmVersion_SingleVersion2
        {
            get
            {
                return ResourceManager.GetString("frmVersion_SingleVersion2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_SearchPattern
        {
            get
            {
                return ResourceManager.GetString("frmMain_tvMain_SearchPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_Settings_Common
        {
            get
            {
                return ResourceManager.GetString("frmMain_tvMain_Settings_Common", resourceCulture);
            }
        }

        


        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmVersion_Title1
        {
            get
            {
                return ResourceManager.GetString("frmVersion_Title1", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmVersion_Title2
        {
            get
            {
                return ResourceManager.GetString("frmVersion_Title2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string MESSAGE_ERROR_DOWNLOAD
        {
            get
            {
                return ResourceManager.GetString("MESSAGE_ERROR_DOWNLOAD", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_Settings_Security
        {
            get
            {
                return ResourceManager.GetString("frmMain_tvMain_Settings_Security", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string MESSAGE_TEST
        {
            get
            {
                return ResourceManager.GetString("MESSAGE_TEST", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_Settings_Repository
        {
            get
            {
                return ResourceManager.GetString("frmMain_tvMain_Settings_Repository", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string program_prompt_title
        {
            get
            {
                return ResourceManager.GetString("program_prompt_title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string program_prompt_description
        {
            get
            {
                return ResourceManager.GetString("program_prompt_description", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_Settings
        {
            get
            {
                return ResourceManager.GetString("frmMain_tvMain_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_SearchCount_Amount
        {
            get
            {
                return ResourceManager.GetString("frmMain_tvMain_SearchCount_Amount", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_SearchCount_Zero
        {
            get
            {
                return ResourceManager.GetString("frmMain_tvMain_SearchCount_Zero", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_SearchCount_One
        {
            get
            {
                return ResourceManager.GetString("frmMain_tvMain_SearchCount_One", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_Detail_MinVersion_Default
        {
            get
            {
                return ResourceManager.GetString("frmMain_Detail_MinVersion_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string frmMain_Detail_Parents_ColumnHeader
        {
            get
            {
                return ResourceManager.GetString("frmMain_Detail_Parents_ColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Verzeichnis konnte nicht erstellt werden. \r\n Bitte prüfen Sie die Berechtigungen für den Pfad: ähnelt.
        /// </summary>
        internal static string CVersionLookupHelper_CannotCreateDirectory {
            get {
                return ResourceManager.GetString("CVersionLookupHelper_CannotCreateDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die &quot;VersionLookup.xml&quot; konnte nicht geladen werden. \r\n Bitte prüfen Sie die Berechtigungen oder ob die Datei von einem Prozess verwendet und gesperrt wird. ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_Title_Error
        {
            get
            {
                return ResourceManager.GetString("frmMain_Dlg_Title_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die &quot;VersionLookup.xml&quot; konnte nicht geladen werden. \r\n Bitte prüfen Sie die Berechtigungen oder ob die Datei von einem Prozess verwendet und gesperrt wird. ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_Title_Question
        {
            get
            {
                return ResourceManager.GetString("frmMain_Dlg_Title_Question", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die &quot;VersionLookup.xml&quot; konnte nicht geladen werden. \r\n Bitte prüfen Sie die Berechtigungen oder ob die Datei von einem Prozess verwendet und gesperrt wird. ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_PathToExport_Title
        {
            get
            {
                return ResourceManager.GetString("frmMain_Dlg_PathToExport_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die &quot;VersionLookup.xml&quot; konnte nicht geladen werden. \r\n Bitte prüfen Sie die Berechtigungen oder ob die Datei von einem Prozess verwendet und gesperrt wird. ähnelt.
        /// </summary>
        internal static string CVersionLookupHelper_CannotLoadXML {
            get {
                return ResourceManager.GetString("CVersionLookupHelper_CannotLoadXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die &quot;VersionLookup.xml&quot; konnte nicht gespeichert werden. \r\n Bitte prüfen Sie die Berechtigungen oder ob die Datei von einem Prozess verwendet und gesperrt wird. ähnelt.
        /// </summary>
        internal static string CVersionLookupHelper_CannotSaveXML {
            get {
                return ResourceManager.GetString("CVersionLookupHelper_CannotSaveXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine interne Referenz auf das dazugehörige XML-Element konnte nicht ermittelt werden.  ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_TagNotFound {
            get {
                return ResourceManager.GetString("frmMain_Dlg_TagNotFound", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie den folgenden Mandanten, inkl. aller Untereinträge, wirklich entfernen? \r\n Mandant: ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_DeleteClient {
            get {
                return ResourceManager.GetString("frmMain_Dlg_DeleteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie den folgenden Ordner, inkl. aller Untereinträge, wirklich entfernen? \r\n Ordner: ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_DeleteLogical {
            get {
                return ResourceManager.GetString("frmMain_Dlg_DeleteLogical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie den folgenden Download, inkl. aller Untereinträge, wirklich entfernen? \r\n Download: ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_DeletePhysical {
            get {
                return ResourceManager.GetString("frmMain_Dlg_DeletePhysical", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie den folgenden Download, inkl. aller Untereinträge, wirklich entfernen? \r\n Download: ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_CreateEntry
        {
            get
            {
                return ResourceManager.GetString("frmMain_tvMain_CreateEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie das folgende Produkt, inkl. aller Untereinträge, wirklich entfernen? \r\n Produkt: ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_DeleteProduct {
            get {
                return ResourceManager.GetString("frmMain_Dlg_DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Name darf nicht leer sein. ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_EmptyLabel {
            get {
                return ResourceManager.GetString("frmMain_Dlg_EmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Name enthält ungültige Zeichen. ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_InvalidLabel {
            get {
                return ResourceManager.GetString("frmMain_Dlg_InvalidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Laden des Versions-Baums ist ein Fehler aufgetreten: ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_LoadTreeview {
            get {
                return ResourceManager.GetString("frmMain_Dlg_LoadTreeview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versionen ähnelt.
        /// </summary>
        internal static string frmMain_tvMain_Versions {
            get {
                return ResourceManager.GetString("frmMain_tvMain_Versions", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versionen ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_EncryptFile_Error
        {
            get
            {
                return ResourceManager.GetString("frmMain_Dlg_EncryptFile_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versionen ähnelt.
        /// </summary>
        internal static string frmMain_Dlg_EncryptFile_Success
        {
            get
            {
                return ResourceManager.GetString("frmMain_Dlg_EncryptFile_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versionen ähnelt.
        /// </summary>
        internal static string DOWNLOAD_CANCELLED
        {
          get
          {
            return ResourceManager.GetString("DOWNLOAD_CANCELLED", resourceCulture);
          }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versionen ähnelt.
        /// </summary>
        internal static string INVALID_VERSION_FILE
        {
          get
          {
            return ResourceManager.GetString("INVALID_VERSION_FILE", resourceCulture);
          }
        }  
    
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versionen ähnelt.
        /// </summary>
        internal static string CONFIGURATION_FILE_COULD_NOT_LOAD
        {
          get
          {
            return ResourceManager.GetString("CONFIGURATION_FILE_COULD_NOT_LOAD", resourceCulture);
          }
        }


        internal static string frmMain_Dlg_InvalidEmailFormat
        {
            get
            {
                return ResourceManager.GetString("frmMain_Dlg_InvalidEmailFormat", resourceCulture);
            }
        }

        internal static string frmMain_Dlg_InvalidURLFormat
        {
            get
            {
                return ResourceManager.GetString("frmMain_Dlg_InvalidURLFormat", resourceCulture);
            }
        }

        

    }
}
